POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "email": "Rohan@gmail.com",
    "password": "Rohan123"
}

###

GET http://localhost:3000/profile

###

GET http://localhost:3000/todos/1

###

PUT http://localhost:3000/todos/3
content-type: application/json

{
    "title": "updatedtitle",
    "completed": false
}

###

PATCH http://localhost:3000/todos/3
content-type: application/json

{
    "title": "updatedtitleee"
}

###

DELETE http://localhost:3000/todos/1